version: "3.9"

services:
  # === AUTH SERVICE ===
  auth-service:
    build: ./services/auth-service
    container_name: auth_service
    env_file:
      - ./services/auth-service/.env
    ports:
      - "8000:8000"
    volumes:
      - ./services/auth-service:/app
      - ./certs/BaltimoreCyberTrustRoot.pem:/etc/ssl/certs/BaltimoreCyberTrustRoot.pem:ro
    environment:
      DATABASE_URL: "mysql+pymysql://adminpet:PetTrack2025@pettrack-mysql.mysql.database.azure.com:3306/vet_auth?ssl_ca=/etc/ssl/certs/BaltimoreCyberTrustRoot.pem"
    restart: always

  # === PETS SERVICE ===
  pets-service:
    build: ./services/pets-service
    container_name: pets_service
    env_file:
      - ./services/pets-service/.env
    ports:
      - "8001:8000"
    volumes:
      - ./services/pets-service:/app
      - ./certs/BaltimoreCyberTrustRoot.pem:/etc/ssl/certs/BaltimoreCyberTrustRoot.pem:ro
    environment:
      DATABASE_URL: "mysql+pymysql://adminpet:PetTrack2025@pettrack-mysql.mysql.database.azure.com:3306/vet_pets?ssl_ca=/etc/ssl/certs/BaltimoreCyberTrustRoot.pem"
    restart: always

  # === APPOINTMENTS SERVICE ===
  appointment-service:
    build: ./services/appointment-service
    container_name: appointment_service
    env_file:
      - ./services/appointment-service/.env
    ports:
      - "8002:8000"
    volumes:
      - ./services/appointment-service:/app
      - ./certs/BaltimoreCyberTrustRoot.pem:/etc/ssl/certs/BaltimoreCyberTrustRoot.pem:ro
    environment:
      DATABASE_URL: "mysql+pymysql://adminpet:PetTrack2025@pettrack-mysql.mysql.database.azure.com:3306/vet_appointments?ssl_ca=/etc/ssl/certs/BaltimoreCyberTrustRoot.pem"
    restart: always

  # === API GATEWAY (FastAPI) ===
  api-gateway:
    build: ./services/api-gateway
    container_name: api_gateway
    ports:
      - "8003:8003"
    env_file:
      - ./services/api-gateway/.env
    environment:
      AUTH_SERVICE_URL: "http://auth-service:8000"
      PETS_SERVICE_URL: "http://pets-service:8000"
      APPOINTMENTS_SERVICE_URL: "http://appointment-service:8000"
    depends_on:
      - auth-service
      - pets-service
      - appointment-service
    restart: always

  # === WEB CLIENT (REACT / VITE) ===
  client:
    build: ./client-react
    container_name: web_client
    ports:
      - "5173:8080"
    depends_on:
      - api-gateway
    environment:
      VITE_API_URL: "http://api-gateway:8003"
    restart: always

volumes:
  auth_data:
  pets_data:
  appointments_data:
